### ISSUE TITLE
Xbox not see rpi pico bios install on older version

### ISSUE THREAD

**Issue by M007P** [shalxmva/modxo#1]
Can you update install guide for older version 1.0 to 1.5 with pic if posible .

I have Xbox OG 1.1( have more Xbox OG rev ) on witch i installed 2 pico zeros to test and not load Cerber bios logo just default bios animation.
If need info instaled and no HDD, DVD instaled when testing.

Lifting bios leg on board is needed only for rev 1.6/1.6b ?

Thanks for support

**Comment by yakaracolombia** [comment]
you need to get frame from the mpcx, https://xboxdevwiki.net/LPC_Debug_Port

**Comment by M007P** [comment]
i found out in the morning D0 to GND :-), been tiered and missed.
Found out that black rpi pico not working,  picture below. 
do not buy this RPI PICO for modchip
![IMG_3644](https://github.com/shalxmva/modxo/assets/5527205/800ced19-6b5f-47af-8065-ce0894564ab9)

Classic model works as should, no new revisons of rpi pico works.

**Comment by M007P** [comment]
i used 4 x 100ohm 0805 with pink RPI😂 Barbie style 
no problem. 
![IMG_3645](https://github.com/shalxmva/modxo/assets/5527205/c08b395b-cb81-404f-97b0-5b047487b6f2)
![IMG_3647](https://github.com/shalxmva/modxo/assets/5527205/0e5155ed-25fa-428c-9145-e3aa5470485e)

**Comment by yakaracolombia** [comment]
do you wire the Lframe from mpcx or just d0 to gnd?

**Comment by davidxgames** [comment]
@yakaracolombia  

consoles 1.0 - 1.2 only D0 to gnd
consoles 1.3 - 1.5 D0 to gnd, and mpcx
1.6 consoles rebuild LPC and lift Cyclops chip pin

**Comment by M007P** [comment]
i have done one console rev 1.3 by date with ?? on wiki, needed Lframe from MPCX to work. On console info show rev 1.2. D0 to GND.

> do you wire the Lframe from mpcx or just d0 to gnd?

It was rev 1.1 not needed.

**Comment by shalxmva** [comment]
> i found out in the morning D0 to GND :-), been tiered and missed. Found out that black rpi pico not working, picture below. do not buy this RPI PICO for modchip ![IMG_3644](https://private-user-images.githubusercontent.com/5527205/313434614-800ced19-6b5f-47af-8065-ce0894564ab9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjUxODMsIm5iZiI6MTcxMDgyNDg4MywicGF0aCI6Ii81NTI3MjA1LzMxMzQzNDYxNC04MDBjZWQxOS02YjVmLTQ3YWYtODA2NS1jZTA4OTQ1NjRhYjkuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjQyOTU5MDQwYTI2NmM0NWZmMjI0NmQ0ZTViYjU3ZWM1Mzk1OWNkMTBmMmU4ZjUwOTY4ZTVkZDI5YjFjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tsFcjKUfZfmqteOeN7fpuTnU3cpDWbXdWH4XaP9Rg-g)
> 
> Classic model works as should, new revisons of rpi pico not working.

That version is working for me, 
but i tested other black models and a green clone that doesnt have any raspberry logos to no work.

Which size number your resistors are?

**Comment by M007P** [comment]
> > i found out in the morning D0 to GND :-), been tiered and missed. Found out that black rpi pico not working, picture below. do not buy this RPI PICO for modchip ![IMG_3644](https://private-user-images.githubusercontent.com/5527205/313434614-800ced19-6b5f-47af-8065-ce0894564ab9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjUxODMsIm5iZiI6MTcxMDgyNDg4MywicGF0aCI6Ii81NTI3MjA1LzMxMzQzNDYxNC04MDBjZWQxOS02YjVmLTQ3YWYtODA2NS1jZTA4OTQ1NjRhYjkuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjQyOTU5MDQwYTI2NmM0NWZmMjI0NmQ0ZTViYjU3ZWM1Mzk1OWNkMTBmMmU4ZjUwOTY4ZTVkZDI5YjFjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tsFcjKUfZfmqteOeN7fpuTnU3cpDWbXdWH4XaP9Rg-g)
> > Classic model works as should, new revisons of rpi pico not working.
> 
> That version is working for me, but i tested other black models and a green clone that doesnt have any raspberry logos to no work.
> 
> Which size number your resistors are?

its 0805 size i had
only them

**Comment by Androxilogin** [comment]
Hah, I had two questions that were both answered here:

1) is this compatible with boards other than the v1.6?
2) Does the v1.6 require LPC rebuild?

Thanks for clearing this up by asking the same questions I had.

**Comment by M007P** [comment]
all solved
