### ISSUE TITLE
LOGO para modxo

### ISSUE THREAD

**Issue by dachronos** [shalxmva/modxo#12]
Buen dia bro
Se que ya tienes un logo pero tu proyecto me inspiro bastante e hice aqui uno minimal mezclando las letras "X" y "O" hice algunas variantes por si te sirven o deseas incluirlas, es un gran trabajo y un orgullo en la comunidad del hardmodding hispanohablante! 😄 
un saludo y un abrazo desde MTY

aqui te dejo una vista previa y un zip con el logo 😁

![horizontal negro color](https://github.com/shalxmva/modxo/assets/13940942/bba33259-adcc-41b5-8954-0eab8e915206)

[logo modxo y variantes.zip](https://github.com/shalxmva/modxo/files/15134232/logo.modxo.y.variantes.zip)

**Comment by shalxmva** [comment]
Muchas gracias!
