### ISSUE TITLE
Colab modxo Builder

### ISSUE THREAD

**Issue by eolandro** [shalxmva/modxo#13]
Hi

Maybe this is a kind of useless. But this colab can clone, build and download a new  fresh firmware  from modxo main repository.

i wanna make a VM for Windows users, but maybe later.

[Here](https://github.com/eolandro/BuildThings/tree/main/modxo)

PD. Sorry for bad english

**Comment by eolandro** [comment]
Well
[Here](https://drive.google.com/file/d/10eMPMBz14Fz1az4P8wqYdSiYFHb-f6cy/view?usp=drivesdk) is the virtual machine for virtual box. It's a debian (Antix) X86_64. 2 GB of RAM is needed.

Features:

- SSH server
- FTP server
- CMake
- Arm-none-eabi cross compiler
- Pico-SDK
- Latest-modxo code

No GUI included.

Username: modxo
Password: modxo

if someone can tested it will be great!

**Comment by shalxmva** [comment]
Voy a probarlo!!

**Comment by eolandro** [comment]
Debería funcionar con la nueva versión, según mis pruebas, un git pull en la carpeta de modxo seria suficiente.

it must be work with new version. Just "git pull" in the modxo directory is needed

**Comment by shalxmva** [comment]
Gracias!
