### ISSUE TITLE
rp2040 tiny support?

### ISSUE THREAD

**Issue by IITuxtmuxII** [shalxmva/modxo#14]
is there a rp2040 tiny support planned?

**Comment by IITuxtmuxII** [comment]
also is it posible to flash it via xblast?

**Comment by shalxmva** [comment]
Havent tested it yet, but i assume is the same pinout as rp2040 zero.
RP2040 zero is compatible.

**Comment by shalxmva** [comment]
I am not currently working on any xbox application, but surely it will be flashable in a future

**Comment by shalxmva** [comment]
Could you please test rp2040 tiny with "v0.2"?

**Comment by k3nnk3nn** [comment]
Tt's weird none of rp2040 including tiny is working when I flashed them with v0.2. All of them are working fine with v0.1. Although I've reflashed from scratch using flash_nuke. Now, I'm rolling back to v0.1.

**Comment by shalxmva** [comment]
Thanks i will check that.

**Comment by DynaMight1124** [comment]
RP2040 Tiny deffo works. I built one, initially running beta 0.0, I didnt get around to trying 0.1 but just flashed 0.2 and its still working fine with Cerbios with my v1.1 Xbox. 

I'm not sure if this has any bearing but my d0 is tied directly to ground, not to the RP2040 at all.
