### ISSUE TITLE
Xiao RP2040 support? 

### ISSUE THREAD

**Issue by howdid1gethere** [shalxmva/modxo#17]
Would this be possible at all? Looking at this image, it appears that all required pins are there except for pin7 for 1.6 D0. Could that signal be found elsewhere on the Xiao? 

![xiao-rp2040-pin.jpg](https://github.com/shalxmva/modxo/assets/149995092/afe65d0d-8adb-420b-b42c-9adf410237c6)

**Comment by shalxmva** [comment]
LFrame is not available.
So if you want to make it to work with v1.6, you must modify source code (Just the LFrame pin define on LPC_comm.pio)
and recompile it.

<img width="372" alt="image" src="https://github.com/shalxmva/modxo/assets/5183445/071d084b-6ce8-49f6-986a-683382185cf0">

That should work

**Comment by howdid1gethere** [comment]
Apologies, I got D0 and LFrame mixed up. On the underside of the board there are direct solder points for VIN and GND. Schematic below.

![61d6f2876fd2d.jpeg](https://github.com/shalxmva/modxo/assets/149995092/46f59d76-9bf3-4163-8b85-11e24a988927)

![Screenshot_20240519-233754.png](https://github.com/shalxmva/modxo/assets/149995092/01a84555-3313-488f-9897-fc9415a9347f)

Thank you for your help.

**Comment by howdid1gethere** [comment]
If the software is just utilizing the pins as gpio, would gpio pin 7 in the software not still translate to gpio pin 7 regardless of the board?

**Comment by howdid1gethere** [comment]
I think my brain just caught up with my project. Consider this closed and I'll report back.

**Comment by shalxmva** [comment]
> If the software is just utilizing the pins as gpio, would gpio pin 7 in the software not still translate to gpio pin 7 regardless of the board?

Xiao-rp2040 pin names doesnt directly match. But using gpio7 is the same for all, but you have to check where that pin is connected to which pin.

**Comment by howdid1gethere** [comment]
I understand. Working on implementation now
