### ISSUE TITLE
No Display

### ISSUE THREAD

**Issue by johnl6234** [shalxmva/modxo#18]
I have a verion 1.1, when I load in cerbios the led ring goes green but I get no display.

im using an original pipico 
![IMG_20240522_100421](https://github.com/shalxmva/modxo/assets/47853652/01078298-2094-476c-8a0a-8835ce8f779f)
the thin white wire goes to DO on the back of the board

I've used all 3 versions and they all do thesame except V0.1 this is the only version where the onboard led flashed after loading modxo.uf2

Ive tried all versions of cerbios 2.3.2 UDMA2 - UMDA6

Steps I do:

I Plug in the Pipico into bootsel and load flash_nuke.uf2.
I then unplug the pico and reboot into bootsel and load modxo.uf2.
I then unplug the pico and reboot into bootsel and load Cerbios.uf2

Im not sure if I doing this correct.

**Comment by shalxmva** [comment]
Could you please try with another bios?
maybe Evox

**Comment by johnl6234** [comment]
The only Evox bios that will show a screen is Evox V2.6 - V1.0 but that doesnt have the error 16 patch that I need

**Comment by johnl6234** [comment]
The problem seemed to be the bios uf2 files coming from the website, when I convert the bin files using flashbin_to_uf2.py it works

**Comment by shalxmva** [comment]
Could you please attach a working and non working file?
So I can compare differences.

Thanks
