### ISSUE TITLE
Aplicacion ejecutable en windows para convertir bios

### ISSUE THREAD

**Issue by CarlosValdes** [shalxmva/modxo#2]
shalxmva, use tu codigo para hacer  un ejecutable en windows para convertir la bios seleccionando el archivo .bin y carpeta destino, no he tenido oportunidad  de hacer pruebas, la comparacion de archivos entre esta app y el script da igual (utilice todo tu script jejeje), creo que habra gente a la que le puede ayudar ya que no necesitan instalar python

![appconvertir](https://github.com/shalxmva/modxo/assets/26008585/cc3c6502-30c9-46ca-accc-b477f54fc585)
![2024-03-15 23_11_05-Abrir](https://github.com/shalxmva/modxo/assets/26008585/08a65da0-8c03-4021-b046-b5c8743d4ec0)
![2024-03-15 23_11_52-carpeta](https://github.com/shalxmva/modxo/assets/26008585/952241c6-207c-463d-b7b6-a6931a54cc4c)
![2024-03-15 23_12_24-app](https://github.com/shalxmva/modxo/assets/26008585/7fe2ca98-70bf-4063-80b8-3889ff52a6ed)
![2024-03-15 23_16_29-Convertir BIOS bin a uf2](https://github.com/shalxmva/modxo/assets/26008585/45333696-619c-42ae-9e9c-ccd2491c339b)

**Comment by shalxmva** [comment]
Ezcelente

**Comment by shalxmva** [comment]
Por cierto, opté por un diseño que corra en browser, para hacer que la conversión sea más rapida sin tanto click, solo arrastrar el archivo a la pagina web.

    [Bios Packer](https://shalxmva.github.io/modxo)

¿Qué framework usaste para hacer la ventana?

Saludos

**Comment by dachronos** [comment]
Apenas sacar una version asi con electron tipo las extensiones de After Effects, que nadamas arrastras el archivo a la ventana y se ejecuta todo 👀
