### ISSUE TITLE
Support on version 1.0

### ISSUE THREAD

**Issue by luisfcorreia** [shalxmva/modxo#21]
Hi, 
following Tito's video I tried to use this mod on a version 1.0 motherboard, using an original Pico and Pico W.

None of the ROM's I tried worked, (even the one extracted from my Alladin modchip) and the interesting thing is that if I use one of the original release xbox bios, it starts to boot loop

In none of these instances I got any video output from the system.

I tried using the source code compiled locally as well as the 0.2Beta release.

Am willing to try and experiment with everything you deem necessary ;)

Thanks for a great project!

**Comment by MrKittenK** [comment]
Have you checked all solder joints 
Have you got D0 grounded or connected to the ModXo? 

Cheers

**Comment by luisfcorreia** [comment]
I'm about to give up for now, none of these Pico boards work.

Granted, my resistors are not 100Ohm, they are 130 and 120.

![1000006917](https://github.com/shalxmva/modxo/assets/191885/b9c00572-d877-4593-8105-01377044cb42)

with either one of these connectrd, the console does not show any image

Same results on 1.0 and 1.6, the two consoles I have

Feel free to ask me for more stuff

**Comment by shalxmva** [comment]
Let me check with 120 Ohm resistors.

**Comment by luisfcorreia** [comment]
as a side note, I found out that the waveshare pico was a bit warmer to the touch then the original (it may mean nothing at all)

**Comment by shalxmva** [comment]
I Still haven't found anything. I am configuring a debugger so i can find out more.

**Comment by luisfcorreia** [comment]
This hasn't worked for me and I've now lost interest in it.

Will keep an eye on the project but will close this issue.

Good luck with further development.

**Comment by jpeg2600** [comment]
Just adding that it's working on a 1.0 over here but the video is glitched while using a components cable, it's fine using a normal composite one.
