### ISSUE TITLE
problema de sonido

### ISSUE THREAD

**Issue by serviciosinformaticos** [shalxmva/modxo#22]
Hola, primero que nada queria agradecer tu esfuerzo, queria comentarte que utilize el mod tuyo y la consola anda barbara (1.6), el unico problema, es que no tengo sonido (la utilizo con cable a/v comun), la unica forma que tengo de que "agarre" sonido, es desenchufar y enchufar el cable A/V en caliente (cuando la consola esta prendida), automaticamente luego e inmediatamente de hacer eso, la consola funciona con sonido PERFECTO, buen volumen sin interferencias, pero solo cuando hago ese procedimiento, que puede ser?

**Comment by shalxmva** [comment]
Hola, eso está raro. El modxo no interviene para nada en la generación de sonido.

**Comment by shalxmva** [comment]
Tal vez alguna soldadura fria?
No tengo idea de que pudiera ser. Tal vez alguien con mayor experiencia técnica pueda ayudarte.
