### ISSUE TITLE
LPC update + Cerbios 2.4.0 beta reset issue

### ISSUE THREAD

**Issue by antoxa2584x** [shalxmva/modxo#27]
Checked newest version with LPC fix, on 1.6b motherboard reset follows to cerbios logo and nothing then

**Comment by rdmrocha** [comment]
There a 2.4.1 out. You may want to double-check with it

**Comment by antoxa2584x** [comment]
UPD: After reset seems like Cerbios load twice. There is small black screen blink between logos. Load time if each same as cold boot

**Comment by shalxmva** [comment]
Could you please try with new release?
But from the new Repo:

https://github.com/Team-Resurgent/Modxo

**Comment by antoxa2584x** [comment]
Can’t test now. Sold Xbox with mod. Will try with new one in few weeks probably

**Comment by shalxmva** [comment]
Ok. For any other issues you have, please open an issue in the new repo: https://github.com/Team-Resurgent/Modxo

Thanks!!!!

**Comment by shalxmva** [comment]
Even if it is the sme issue
