### ISSUE TITLE
LPC Rebuild information

### ISSUE THREAD

**Issue by DrNotThatEvil** [shalxmva/modxo#31]
Hi, and thanks for the work on modxo!
I got a xbox 1.6 a while ago intending to mod it with a aladdin chip
but i could not get my LPC rebuild to work, thinking i must have
messed something up or just bought a faulty chip I put the xbox in my:
"projects for later pile"

But a a few weeks ago I stumbled on this project and since
i love the idea of using available and cheap chips to replace old modchips I dug my xbox out of the pile.

Sadly the modsho did not boot my xbox into any bios
(i just got a red green blinking power light), since i suspect my soldering might not be
the best i have rebuild my lpc rebuild again but even after this no dice.

So my question is, could you provide a LPC rebuild diagram that is know to be good?
Since some rebuilds say to tie some things to ground, some talk about a D0 line? 

I ask since i kind of get lost in the weeds finding old resources, so stumbeling on old information, broken links and outdated info is part for the course.

Second question, I know from looking into my LPC rebuild that pcb's exist that help rebuild the LPC port, and i was wondering if you have tried any?

Thanks and sorry for the long message,
thought i ask for help fist before retrying a LPC rebuild in this hot summer weather :smile:

**Comment by rdmrocha** [comment]
![image](https://github.com/user-attachments/assets/f0dc131f-bd34-4220-b4d9-26c725db112d)

**Comment by shalxmva** [comment]
Hi, i am going to try this PCB:

https://github.com/Kekule-OXC/OXC_LPCorrectr
