### ISSUE TITLE
FRAG on 1.6 Xbox after powered off for a bit

### ISSUE THREAD

**Issue by beefstrudel** [shalxmva/modxo#7]
Installing this to a 1.6 board worked great, however when I leave the Xbox powered off for more than a few minutes and try to power on it frags.
Disconnect the 5V and reconnect to the RP2040 and it works again. I think the always on 5V on the 1.6 boards is causing some sort of issue. I added an inline switch to the 5V wire so I can just power it off when the Xbox is off. As long as I power the chip off and back on before I power on the Xbox it always works.

**Comment by shalxmva** [comment]
We are making a further analysis on that.
Could you please post a picture of the RP2040 board you are using?

**Comment by beefstrudel** [comment]
Sure thing! I removed the 5V from the LPC itself and soldered it to the transistor near the video connector since it was a switched 5V, seems to work fine with that setup. 

To recreate the issue solder the chip to the always on 5V on the LPC bus, leave the Xbox plugged in but powered off for 15-20 minutes and it'll frag. 

![20240416_104550](https://github.com/shalxmva/modxo/assets/16218039/4838b473-b98a-4235-82e3-cc769a233d81)
![20240416_104542](https://github.com/shalxmva/modxo/assets/16218039/2bc0e949-bf92-4a2f-94d8-12ef18b87945)

**Comment by pblyp** [comment]
I have the same thing with my 1.6, left it for a couple of days powered off and connected to the mains and it frags. Disconnecting the Xbox from mains for ~30 minutes is the only way to actually make modxo work again without disassembling the console. @beefstrudel could you please show where is that exact transistor I can try connecting 5V to?

**Comment by beefstrudel** [comment]
> I have the same thing with my 1.6, left it for a couple of days powered off and connected to the mains and it frags. Disconnecting the Xbox from mains for ~30 minutes is the only way to actually make modxo work again without disassembling the console. @beefstrudel could you please show how you connect RP2040 to the video out transistor?

Here ya go! 
![x3_alt5v jpg 07cec4cb13f4e196d04965b726df9b34](https://github.com/shalxmva/modxo/assets/16218039/d0677a03-7cf2-442d-834e-a48fd9e6f2c9)

**Comment by shalxmva** [comment]
I want to make a quick experiment.
Without any usb cable connected, Could you please connect 3.3v from LPC to VSYS pin on Pico?

Apparently the voltage regulator gets hot and stops feeding the RP2040.

Thanks for your help!!!

**Comment by BananaFaction** [comment]
> I want to make a quick experiment. Without any usb cable connected, Could you please connect 3.3v from LPC to VSYS pin on Pico?
> 
> Apparently the voltage regulator gets hot and stops feeding the RP2040.
> 
> Thanks for your help!!!

In theory I think that should work since the rp2040 is made to take 3.3 volts even though it's supposed to work with 5v because of the voltage regulator.

**Comment by BananaFaction** [comment]
Can now confirm that using the 3.3v pin cerbios booted up.
![20240515_204743](https://github.com/shalxmva/modxo/assets/37634694/b7c3c8c7-78a7-4d20-90f2-5932399a602f)

**Comment by shalxmva** [comment]
> Can now confirm that using the 3.3v pin cerbios booted up. ![20240515_204743](https://private-user-images.githubusercontent.com/37634694/330999165-b7c3c8c7-78a7-4d20-90f2-5932399a602f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Njc2MTcsIm5iZiI6MTcxNTg2NzMxNywicGF0aCI6Ii8zNzYzNDY5NC8zMzA5OTkxNjUtYjdjM2M4YzctNzhhNy00ZDIwLTkwZjItNTkzMjM5OWE2MDJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEzNDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyM2U4MGZiMGE1YTBmNjAwZmM1Njk3MjQ3ODJmODQ1YzU0YjEyODYxZmUwMDRjMzM5MjgyNzkzNGQ3OTRlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H2uwpOQyTmtEj5wW5cN2QKC_mIQBqdoA6PFSNrkTnsY)

But dont connect a usb cable while connected to Xbox 3.3v pin. Or if you need it, you must add a Diode from 3.3v pin to VSYS.

**Comment by BananaFaction** [comment]
Yeah if I need to flash th rp2040 I'll probably unhook it from the board to bring to my pc then connect the USB only. But thanks for reminding me of that fact.

**Comment by shalxmva** [comment]
Thanks, there are other boards that have a diode, but those label that pin as Vin.
Please feel free to report any issue.
