### ISSUE TITLE
Problems with a 1.6b Xbox

### ISSUE THREAD

**Issue by satresar** [shalxmva/modxo#9]
Hello, I'm having  a problem using modxo on a 1.6b Xbox (The one with Hynix RAM chips). I have already rebuild the LPC but no matter what I try, it just boot up on the stock BIOS. This Xbox was using a Aladdin XT chip to boot up, so the LPC rebuild is techniclly good, exept that the LFRAME point in the board was conected to the Aladdin XT chip on the D0 point and BT and L1 points were conected to referd points. I tried to ground the LFRAME point but the Xbox just FRAG.  Any idea in what is going on? I'm gonna leave some pictures here to see if anything is wrong.

In adition to this, I'm very new to the Rasberry PI Pico, so there is any way to see if the Pi Pico is working as intended? Like a serial monitor on the PC. I have been following the project since the launch and in the instructions it says that the LED on the PI Pico will blink if there is no BIOS file, is it still working that way? If so, shoud it be blinking while it conected to the PC? I'm sorry if this is a really long message but I'm very interested on doing a 128 MB RAM mod and modchip with Xblast its kinda required.

This is how the LPC rebuild looks like
![WhatsApp Image 2024-04-20 at 3 17 29 PM](https://github.com/shalxmva/modxo/assets/167648170/30384f87-495c-45a5-88af-64f7164b0291)

And this is my build of the Modxo chip.
![WhatsApp Image 2024-04-20 at 3 17 32 PM](https://github.com/shalxmva/modxo/assets/167648170/04fda7ec-e1e1-4c2d-b21f-1906cb6eafe2)
![WhatsApp Image 2024-04-20 at 3 17 29 PM (1)](https://github.com/shalxmva/modxo/assets/167648170/749174e2-2627-4dae-96b3-69e3de57ded7)

Btw, saludos desde Colombia, quisiera haber escrito todo en español pero me parece mejor si lo escribía en ingles y si de ser posible me puedas responder en ingles por si alguien tiene el mismo problema en el futuro y no sabe español.

**Comment by satresar** [comment]
So, I found what's causing to not boot into the BIOS I flash, and it's the Raspberry Pi Pico. Looks like, for whatever reason it doesn't work with ModXo. But the strange event happen here: I order some RPIPICO knockoff

**Comment by shalxmva** [comment]
Hi, i saw from people that there are some boards that didn't work even if those are the same as known working models.
I am trying to improve the code to increase compatibility.

For the LED, it only flashes if there is only the modxo image flashed but no bios.

I am trying to add more error detections. By now, if the LED Flashes, there is an error message printed through the USB Serial Port.
